### ISSUE TITLE
SILDebugCharacteristicTableViewCell~ipad.xib does not include Property Buttons

### ISSUE THREAD

**Issue by martinoneutrino** [SiliconLabs/EFRConnect-ios#2]
In the 1.4.2 release (available [here](http://dropbox.com/s/jxtk0vz5d1k0hvy/Bluegecko-ios.zip?dl=0)), the `SiliconLabsApp/Base.lproj/Debug/Services/SILDebugCharacteristicTableViewCell~ipad.xib` file does not include any of the (Read,Write,Indicate,Notify) Property Buttons that are in the `SILDebugCharacteristicTableViewCell~iphone.xib` file.
This means that when running on an iPad, the Read/Write/etc icons are not interactive, and cause the characteristic value to be shown/hidden, the same as if elsewhere on that row was tapped.

**Comment by silabs-TiagoM** [comment]
Can you see if this is still the case with the latest release (1.5.1 at the time of this comment)?
