### ISSUE TITLE
Minimal code or SDK for DFU firmware update

### ISSUE THREAD

**Issue by tylerjames** [SiliconLabs/EFRConnect-ios#5]
I'd like to implement a feature into my own app that allows a user to update the firmware of a Silicon Labs device. The app also interacts with non-Silicon Labs bluetooth devices in a different manner.

Is there a minimal subset of this code that can be used to handle the DFU upload in my own app? I realize that this is a more of a sample app, but is there an SDK that can be imported? Barring any of that, is there an explanation somewhere for what commands the device expects and how the data could be sent that I could instead use to implement it myself?

Sorry, I know this isn't really an "issue" with this project, I just wasn't sure where else to ask about this.

Thanks

**Comment by silabs-TiagoM** [comment]
> I realize that this is a more of a sample app, but is there an SDK that can be imported?
No, we don't provide any mobile-side SDKs with OTA or any other Silabs specific functionality for BLE. For Bluetooth Mesh we do have an ADK which customers can use to create their own Bluetooth Mesh mobile applications.

The OTA is explained in this application note: https://www.silabs.com/documents/public/application-notes/an1086-gecko-bootloader-bluetooth.pdf. Once you get an understanding of how it works it should be straight-forward, and EFR Connect OTA implementation can be used as a reference.

For future technical inquiries I recommend that you use our community instead: https://www.silabs.com/community/wireless/bluetooth/forum
